---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-vol-nehagupta1-v1-volsnap
  failurePolicy: Fail
  name: mvolsnap.kb.io
  rules:
  - apiGroups:
    - vol.nehagupta1
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - volsnaps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vol-nehagupta1-v1-volsnap
  failurePolicy: Fail
  name: vvolsnap.kb.io
  rules:
  - apiGroups:
    - vol.nehagupta1
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - volsnaps
  sideEffects: None
