---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vol.nehagupta1
  resources:
  - volsnaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vol.nehagupta1
  resources:
  - volsnaps/finalizers
  verbs:
  - update
- apiGroups:
  - vol.nehagupta1
  resources:
  - volsnaps/status
  verbs:
  - get
  - patch
  - update
