# permissions for end users to edit volrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volsnap
    app.kubernetes.io/managed-by: kustomize
  name: volrestore-editor-role
rules:
- apiGroups:
  - vol.nehagupta1
  resources:
  - volrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vol.nehagupta1
  resources:
  - volrestores/status
  verbs:
  - get
