# permissions for end users to view volsnaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volsnap
    app.kubernetes.io/managed-by: kustomize
  name: volsnap-viewer-role
rules:
- apiGroups:
  - vol.nehagupta1
  resources:
  - volsnaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vol.nehagupta1
  resources:
  - volsnaps/status
  verbs:
  - get
